### ISSUE TITLE
Change of location in applet, is not a real time

### ISSUE THREAD

**Issue by fagunbhavsar** [Dirli/budgie-weather-applet#3]
After installing weather applet (Here, Ubuntu 18.10, Budgie Desktop), after selecting initial location, if I want to change this - I am able to do so through applet configuration but the change does not take place in real time. I need to restart the system in order to see the location change

**Comment by Dirli** [comment]
On the configuration applet there is a button "Update Now". If you press it, an update will be performed for the selected city. Catching the event change the city without explicitly informing about it (pressing a button, rebooting), I consider it a bad decision. Extra server requests for input errors.
In the near future I will add automatic positioning.
