### ISSUE TITLE
issue with libgweather 3.28.3 

### ISSUE THREAD

**Issue by vredesbyyrd** [Dirli/budgie-weather-applet#4]
Hi, thanks for sharing this plugin.  

On arch linux `libgweather` was recently updated to `3.28.3`, with that update this plugin no longer pulls in any weather info. The popover and panel just display blank. I tried recompiling hoping to get some clues but it compiles without issue. You can see `libgweather's` relevant commit history [here](https://gitlab.gnome.org/GNOME/libgweather/commits/3.28.3) 

I have not been able to narrow down what change in `3.28.3` is responsible. For now I am just staying on `3.28.2`, but figured I should file this to make the issue known. 

Thanks for your time. Cheers.

**Comment by Dirli** [comment]
I also recently noticed this problem (only I have the forecast was not consistently loaded, not every time). Most likely there is a problem with forecast providers. At the moment I see several ways to solve the problem:
- to request a weather direct from openweathermap. but then users will have to get their own key (the service limits the number of requests and can block the shared key)
- continue with libgweather, and see what's changed. can strictly specify the forecast provider (for example, openweathermap)

I will try to solve this problem in the near future

**Comment by Dirli** [comment]
Hi, I made the following changes:
- the forecast is requested directly from the provider
- if you have problems with the shared api-key, you can add your own
- location can be determined independently (the libgweather is used only here) or automatically by ip

until it is very well tested, if you have time and understanding of what you are doing, you can check it too).

**Comment by vredesbyyrd** [comment]
Thanks for the followup and making these enhancements :)  Tomorrow night I will start testing the changes.  

> the forecast is requested directly from the provider 

Imo, probably the best approach. Ill let you know how it works out. 

Thanks again for your time.

**Comment by vredesbyyrd** [comment]
Closing as this is fixed in master
