### ISSUE TITLE
Panel crashes searching for location

### ISSUE THREAD

**Issue by vredesbyyrd** [Dirli/budgie-weather-applet#6]
#### ENV info: 

- Budgie-Desktop  10.4+250+g0f5a51c8-1 
- Arch linux  
- GTK3 3.24.5-1
- Glib2 2.60.0-1

Hi, I have been testing the latest changes and they look great.  Although I have ran into an issue on commit 9155fb80cfcaaf79563c3c30d010b9a600ee2ca5

- when searching for a location that is not immediately found, the plugin will crash the panel. `nohup budgie-panel --replace&` will bring it back up. 

Here is the log for the panel crash when searching.  I am not very familiar with vala, but if there is anything I can do let me know. 

[budgie-weather-crash-log.txt](https://github.com/Dirli/budgie-weather-applet/files/2954738/budgie-weather-crash-log.txt)

**Comment by vredesbyyrd** [comment]
Interesting, I just discovered the same (or similar) crash is occurring when searching for locations with `Meteo` and `Gnome-Weather`. So this is not limited to your plugin. I will look into this further.  

[meteo-crash.txt](https://github.com/Dirli/budgie-weather-applet/files/2955361/meteo-crash.txt)

**Comment by Dirli** [comment]
Describe in more detail what search means:
- automatic search when there is no internet connection?
- manual search, again with no connection or when the network is on?

Today I will be testing for debian, gento. I will try to check.

**Comment by vredesbyyrd** [comment]
Sorry about that. 

Manual search when connected to network causes crash. Automatic location detection works great and is a nice feature. Although I use a vpn often so manually selecting the location is preferred. 

It appears to crash when parsing certain locations. I have not been able to find a rhyme or reason yet. Will investigate further.  

https://imgur.com/a/Weq7t9a

**Comment by vredesbyyrd** [comment]
Looks like `geocode-glib` is responsible, and there are fixes in master. Will try to compile with the fixes and report back. 

https://gitlab.gnome.org/GNOME/geocode-glib/commit/e1a6b067dc42618992787e84aadad2ca27ae0017

**Comment by vredesbyyrd** [comment]
`Geocode-glib` is indeed responsible. I compiled `geocode-glib` with the latest fixes and manually searching now goes smoothly. 

And I just realized I should have filed a separate bug for the 2nd issue. Was very tired when I reported this last night. Ill close this and resubmit the unrelated issue. 

> detecting/setting metric or imperial units automatically based on location does not work
