### ISSUE TITLE
Metric / Imperial units need to be manually set. 

### ISSUE THREAD

**Issue by vredesbyyrd** [Dirli/budgie-weather-applet#7]
#### ENV info: 

- Budgie-Desktop  10.4+250+g0f5a51c8-1 
- Arch linux  
- GTK3 3.24.5-1
- Glib2 2.60.0-1

Hi, I have been testing the latest changes and here is an issue I have ran into. 

- detecting/setting metric or imperial units automatically based on location ip, or when manually setting the location does not work. I am located in a country that still uses imperial units (stupid) , and I have to manually set the unit via dconf.  

This is not a big deal to me, but figured I should report it nonetheless.

**Comment by Dirli** [comment]
Did not find criteria for automatic selection of units. Manual selection only

**Comment by vredesbyyrd** [comment]
Sounds good, and no worries.
